Traceback (most recent call last):
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Model definition
def dXdt(X,t,L,B,dT,dI,k,c):
  dTdt= L -B*X[0]*X[2] -dT*X[0]
  dIdt= B*X[0]*X[2] - dI*X[0]
  dVdt= k*X[1]-c*X[2]
  return [dTdt,dIdt,dVdt]

X0 = [1e6,0,100]  # initial condition

# solve ODE
tmax,n = 140,401
t = np.linspace(0,tmax,n)
X = odeint(dXdt,X0,t,args=())

# plot results
plt.plot(t,X[:,0],'b--',label='S(t)')
plt.plot(t,X[:,1],'r--',label='I(t)')
plt.plot(t,X[:,2],'k',label='R(t)')
plt.ylabel('values')
plt.xlabel('time')
plt.legend(loc='best')
plt.show()


------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-3-ef7404f4bdf4>[0m in [0;36m<module>[1;34m[0m
[0;32m     11[0m [0mtmax[0m[1;33m,[0m[0mn[0m [1;33m=[0m [1;36m140[0m[1;33m,[0m[1;36m401[0m[1;33m[0m[1;33m[0m[0m
[0;32m     12[0m [0mt[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mlinspace[0m[1;33m([0m[1;36m0[0m[1;33m,[0m[0mtmax[0m[1;33m,[0m[0mn[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 13[1;33m [0mX[0m [1;33m=[0m [0modeint[0m[1;33m([0m[0mdXdt[0m[1;33m,[0m[0mX0[0m[1;33m,[0m[0mt[0m[1;33m,[0m[0margs[0m[1;33m=[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     14[0m [1;33m[0m[0m
[0;32m     15[0m [1;31m# plot results[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\py37\lib\site-packages\scipy\integrate\odepack.py[0m in [0;36modeint[1;34m(func, y0, t, args, Dfun, col_deriv, full_output, ml, mu, rtol, atol, tcrit, h0, hmax, hmin, ixpr, mxstep, mxhnil, mxordn, mxords, printmessg, tfirst)[0m
[0;32m    242[0m                              [0mfull_output[0m[1;33m,[0m [0mrtol[0m[1;33m,[0m [0matol[0m[1;33m,[0m [0mtcrit[0m[1;33m,[0m [0mh0[0m[1;33m,[0m [0mhmax[0m[1;33m,[0m [0mhmin[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    243[0m                              [0mixpr[0m[1;33m,[0m [0mmxstep[0m[1;33m,[0m [0mmxhnil[0m[1;33m,[0m [0mmxordn[0m[1;33m,[0m [0mmxords[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 244[1;33m                              int(bool(tfirst)))
[0m[0;32m    245[0m     [1;32mif[0m [0moutput[0m[1;33m[[0m[1;33m-[0m[1;36m1[0m[1;33m][0m [1;33m<[0m [1;36m0[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    246[0m         [0mwarning_msg[0m [1;33m=[0m [0m_msgs[0m[1;33m[[0m[0moutput[0m[1;33m[[0m[1;33m-[0m[1;36m1[0m[1;33m][0m[1;33m][0m [1;33m+[0m [1;34m" Run with full_output = 1 to get quantitative information."[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: dXdt() missing 6 required positional arguments: 'L', 'B', 'dT', 'dI', 'k', and 'c'
TypeError: dXdt() missing 6 required positional arguments: 'L', 'B', 'dT', 'dI', 'k', and 'c'

