Traceback (most recent call last):
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x=np.linspace(0,np.pi/2,50)           #Define x values

y = np.cos(x) - x

plt.plot(x, y)
plt.xlim(0.6, 0.8)
plt.xylim(0, 1)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_12108\694839286.py[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [0mplt[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mx[0m[1;33m,[0m [0my[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [0mplt[0m[1;33m.[0m[0mxlim[0m[1;33m([0m[1;36m0.6[0m[1;33m,[0m [1;36m0.8[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m [0mplt[0m[1;33m.[0m[0mxylim[0m[1;33m([0m[1;36m0[0m[1;33m,[0m [1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mAttributeError[0m: module 'matplotlib.pyplot' has no attribute 'xylim'
AttributeError: module 'matplotlib.pyplot' has no attribute 'xylim'

